### ISSUE TITLE
Tokenizer functions

### ISSUE THREAD

**Issue by bkrawiec** [CopticScriptorium/tokenizers#6]
@amir-zeldes @ctschroeder 

Note: This is not a problem that needs to be solved but an issue to be addressed in future updates.

1. We have noted that for unpiped files, the tokenizer normalizes. Thus, when converted in Excel there is a tok/"word" (orig_group)/norm layer. I have noticed it does not normalize thetas (e.g. ⲛⲑⲉ is still ⲛ ⲑⲉ and not ⲛ ⲧ ϩⲉ in the norm layer). We need to watch for this. ADDED: Also it does not normalize capitals and the  ̀   and the    ̇   diacritical marks.

2. The processing instructions tell Mac users to use Windows carriage/line breaks for the text file that will be tokenized. This has not worked for me. With Windows line breaks, the tokenizer adds blank lines . When pasted into Excel the converter does not work (you get the error message box). Setting Unix as carriage/line breaks avoids this problem.  This was also true when running the normalizer.

**Comment by amir-zeldes** [comment]
Hi,

 

The tokenizer is breaking up thetas as expected for me. So for nQe (=n+t+he) I get:

 

<norm_group norm_group="ⲛⲑⲉ">

<norm norm="ⲛ">

ⲛ

</norm>

<norm norm="ⲧ">

ⲧ

</norm>

<norm norm="ϩⲉ">

ϩⲉ

</norm>

</norm_group>

 

This is important, since the tokenizer is the preprocessor for the tagger, and tagging won’t recognize the article if it’s not split. Is there maybe something else going on in your examples? The tokenizer is currently failing on capitals, so if the theta (or anything) was capitalized, it will fail.

**Comment by bkrawiec** [comment]
See my other comment. I do not think it did for me when I converted YB, but I will check it again when I convert GL.

**Comment by ctschroeder** [comment]
One more issue to add:  it seems to be breaking ⲥⲟⲛ into ⲥⲟ|ⲛ.  Both Liz and Beth report this issue.  (And I saw it when training Liz.) Lexical?

**Comment by amir-zeldes** [comment]
Hi,

 

I can’t seem to reproduce this. “son” by itself does not get broken up for me. Is there a larger bound group context that this is occurring in or is it just the word “son” standing by itself?

 

Amir

**Comment by ctschroeder** [comment]
ⲁⲟⲩⲥⲟⲛ in one of @ElizabethFD's texts was tokenized as ⲁ|ⲟⲩ|ⲥⲟ|ⲛ (no line break or any other annotation to interfere between o and n).  @eplatte noted then that she remembered seeing this happen in one of her docs with ⲥⲟⲛ, as well.

**Comment by amir-zeldes** [comment]
I had a chance to look at this now - I can reproduce the behavior for a-ou-son. The tokenizer doesn't know this sequence from the segmentation table so it is interpreting it dynamically as a-ou-so-n, with a variant 3rd person spelling of ou for u and a transitive verb with 1st person plural object ("they so-ed us"). 

In general, this behavior is by design based on the priorities of the rules: if something can be a full verbal phrase, that's preferred to just an indefinite subject after an auxiliary. 

The best way to fix this particular problem is to add it to the segmentation table. This will happen naturally the next time I do a big update of the segmentation table based on cumulative progress, but if it's bothering anyone right now, feel free to add it manually to the segmentation table. I wouldn't try changing the order of the rules because of this, since that can cause more, unexpected errors in other places.

**Comment by ctschroeder** [comment]
sounds good. @elizabethFD & @eplatte:  this will get updated the next time we do a major upgrade to the tokenizer (see above)
