### ISSUE TITLE
NLP pipeline tokenizer & thetas binding two tokens

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/tokenizers#8]
One editor noted in NLP pipeline output:  thetas that include a ⲧ and ϩ in two different tokens (e.g., ⲛⲑⲉ) were being processed improperly.  The separate ⲧ and ϩ were appearing in the tok and orig layers.  Editors have been told to keep an eye out so we can document this problem if it happens again.

**Comment by ctschroeder** [comment]
This problem appears in all three Excel sheets the editor was working on, so it seems like it's not human error.

**Comment by amir-zeldes** [comment]
Confirmed. This problem only seems to be affecting the "from pipes in input" option, right? For pure SGML pipeline from plain text I can't reproduce it.

**Comment by ctschroeder** [comment]
I think so.

**Comment by amir-zeldes** [comment]
OK, so, upon thinking about this, there's actually no way for the pipeline to be 100% certain this is a case of t+h. The whole point of having a 'from pipes in input' mode is that the pipeline trusts the user to deliver a perfect tokenization, so the form with theta never gets analyzed. It's approach is like saying; 

"you say it's "n" + "theta" + "e" (nthe) - fine, I believe you."

So in order to turn them into tao + hori, it would need to disbelieve you in this particular case and do an automatic analysis, which is the opposite of "from pipes in input".

The way I see it, we have two options here:

1. When working in "from pipes" mode, theta items should never be trusted. All items containing a boundary adjacent to a theta should be sent to the normal tokenizer routine.
2. Assume that theta items are only ever split theta items if they're in the previous segmentations training data

I think 2 is a bit risky. However 1 could over generate: even if the user gave a correct intended segmentation meant to preserve an actual theta, the "from pipes" mode never believes the user and always sees if it can get an analysis splitting that theta. I don't see much of a way around it though, it seems to be part of the nature of the problem. 

Shall I implement 1? Or do you want to discuss further?

**Comment by ctschroeder** [comment]
I would be interested in @bkrawiec's thoughts.  Could you explain more about what you mean by option 1 "sent to the normal tokenizer routine"?

**Comment by amir-zeldes** [comment]
After discussion with @ctschroeder , strategy 1 has been implemented in 6ea3eebea2df917b093e2896cb589b46d0e4b00c . Groups containing a theta followed by a pipe are now reanalyzed automatically regardless of annotator pipes. This is now live in the pipeline too.
